CREATE TABLE Users(UserID INT IDENTITY(1,1) PRIMARY KEY, Username VARCHAR(100), Email VARCHAR(100)UNIQUE, Password VARCHAR(100));

SELECT * FROM Users;

DROP TABLE Users;

CREATE TABLE Movie(UserID INT FOREIGN KEY REFERENCES Users(UserID), MovieID VARCHAR(100), Poster VARCHAR(1000), Title VARCHAR(100), Year INT, PRIMARY KEY(UserID, MovieID));

SELECT * FROM Movie;

DROP TABLE Movie;


